import os
# To suppress all INFO-level messages, to control the verbosity of log messages generated by TensorFlow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from dgaintel import get_prob

def is_dga(domain):
    prob = get_prob(domain)
    if prob >= 0.75:
        return True
    return False